blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Project Discussions
    url: https://github.com/buenhyden/hy-home.Learned/discussions
    about: Ask questions and share ideas with the community.
  - name: ðŸ“˜ Documentation
    url: https://github.com/buenhyden/hy-home.Learned/tree/main/docs
    about: Access the project's guides and standards.
